library(ggplot2)
results <- read.delim("~/Desktop/results/1/subjects_results.txt", header=T)
t1 = as.numeric(results$Treatment == 1)
t2 = as.numeric(results$Treatment == 2)
t3 = as.numeric(results$Treatment == 3)
results <- cbind(results,t1,t2,t3)
View(results)
write.table(results, file = "~/Desktop/results/1/a.txt", append = FALSE, quote = FALSE, sep = "\t",eol = "\n", na = "NA", dec = ".", row.names = TRUE,col.names = TRUE,fileEncoding = "")

qplot(factor(Treatment), Total, data = results, geom= 'boxplot')
qplot(Total, data = results, geom= 'histogram') + facet_wrap(~ Treatment)
qplot(totaltime, data = results, geom= 'histogram') + facet_wrap(~ Treatment)
qplot(multiplied_gain, data = results, geom= 'histogram') + facet_wrap(~ Treatment)
qplot(s_total, data = results, geom= 'histogram') + facet_wrap(~ Treatment)
qplot(m_total, data = results, geom= 'histogram') + facet_wrap(~ Treatment)
qplot(l_total, data = results, geom= 'histogram') + facet_wrap(~ Treatment)
qplot(factor(Treatment), s_total, data = results, geom= 'boxplot')
qplot(factor(Treatment), m_total, data = results, geom= 'boxplot')
qplot(factor(Treatment), l_total, data = results, geom= 'boxplot')

kruskal.test(multiplied_gain ~ Treatment, data = results)
kruskal.test(s_total_rank ~ Treatment, data = results)
kruskal.test(m_total_rank ~ Treatment, data = results)
kruskal.test(l_total_rank ~ Treatment, data = results)
kruskal.test(s_gain_rank ~ Treatment, data = results)
kruskal.test(m_gain_rank ~ Treatment, data = results)
kruskal.test(l_gain_rank ~ Treatment, data = results)
kruskal.test(totaltime_rank ~ Treatment, data = results)

anova(lm(total_rank ~ factor(Treatment), data = results))
anova(lm(gain_rank ~ factor(Treatment), data = results))
anova(lm(totaltime_rank ~ factor(Treatment), data = results))
anova(lm(total_rank ~ t2 + t3, data = results))
anova(lm(gain_rank ~ t2 + t3, data = results))
anova(lm(totaltime_rank ~ t2 + t3, data = results))
anova(lm(s_total_rank ~ t2 + t3, data = results))
anova(lm(m_total_rank ~ t2 + t3, data = results))
anova(lm(l_total_rank ~ t2 + t3, data = results))
anova(lm(s_gain_rank ~ t2 + t3, data = results))
anova(lm(m_gain_rank ~ t2 + t3, data = results))
anova(lm(l_gain_rank ~ t2 + t3, data = results))
